### ISSUE TITLE
go-oniguruma

### ISSUE THREAD

**Issue by kuba--** [go-enry/go-enry#1]
It's related to `go-oniguruma` fork (not `go-enry`), but I can't create an issue for that repo  (it has to be some persmissions problems).

So, generally the original `https://github.com/moovweb/rubex` package has been archived. Moreover it contains some minor issues. 
That's why we forked and fixed it to `github.com/src-d/go-oniguruma`.

Anyway, to make a long story short - I suggest to make `go-enry/go-oniguruma` fork based on `github.com/src-d/go-oniguruma` instead of `rubex`.

**Comment by mcuadros** [comment]
The content of the `go-enry/go-oniguruma` == `src-d/go-oniguruma` your commits are there: https://github.com/go-enry/go-oniguruma/commits/master

I also enabled the issues on the repo.

Good to see you

**Comment by kuba--** [comment]
ohh, ok - my bad. I thought you just directly forked from rubex.
Thanks, 
Good to see you, too - good luck!
