### ISSUE TITLE
Is it possible to exclude file types?

### ISSUE THREAD

**Issue by ssadeque464** [go-enry/go-enry#108]
Many projects contain makefile, rpms that aren't source code files. Is it possible to exclude file extensions or provide a list of file extensions to ignore from the scan?

**Comment by bzz** [comment]
There are many different use-cases for filtering some of the files out, some are documented at https://github.com/go-enry/go-enry#filtering-vendoring-binaries-etc

The simplest way to achieve what you describe would be to look how [enry CLI binary](https://github.com/go-enry/enry/blob/master/main.go#L62) is using go-enry library to do filtering:
 * run `filepath.Walk()` over the directory, and then for every file
 *  skip the files [you don't need](https://github.com/go-enry/enry/blob/master/main.go#L86), and for the rest
 *  call `enry.GetLanguage(<path>, <content>)` to guess the languages of each file

Hope this helps!
Will going to close the issue, but please feel free to re-open in case something is still not clear, etc.
