### ISSUE TITLE
Mark `go.sum` as generated?

### ISSUE THREAD

**Issue by silverwind** [go-enry/go-enry#132]
Most diffs to go checksum files are pure noise, I'm wondering if anyone else agrees it should be marked as `generated` so tools like gitea can hide diffs on it? Linguist doesn't do it but I think diverging here is fine.

**Comment by lafriks** [comment]
Closing as wont fix to keep compatibility with linguist

**Comment by silverwind** [comment]
It's definitely generated and linguist certainly has some odd decisions regarding generated file where it sees `yarn.lock` as not generated but `package-lock.json` as one. Both files and `go.sum` serve the same purpose, they "snapshot" the dependency tree.

**Comment by lafriks** [comment]
I agree with you on that, reasoning from their side was that changes in yarn.lock and go.sum are usually small and predictable (like lines ar not reordered like in package-json.lock) and so easy to review
