### ISSUE TITLE
IsVendor() overmatching paths

### ISSUE THREAD

**Issue by cboylan** [go-enry/go-enry#135]
I discovered this through our Gitea server flagging files as vendored through its use of enry.IsVendor(). Paths like `oslo_cache/_bmemcache_pool.py` and `playbooks/roles/create-venv/tasks/main.yaml` are inappropriately marked vendored.

My hunch is that the first path is matching https://github.com/go-enry/go-enry/blob/7168084e5e5de38b915b1874528ff73f20a86b69/data/vendor.go#L9
and the second is matching https://github.com/go-enry/go-enry/blob/7168084e5e5de38b915b1874528ff73f20a86b69/data/vendor.go#L110

I've written a little reproducer that removes Gitea from the equation:

```
package main

import "fmt"
import "regexp"
import "github.com/go-enry/go-enry/v2"

func main() {
	input_str1 := "oslo_cache/_bmemcache_pool.py"

	rawregex1, _ := regexp.MatchString(`(^|/)cache/`, input_str1)
	fmt.Println("Raw regex:", rawregex1)

	vendor1 := enry.IsVendor(input_str1)
	fmt.Println("IsVendor:", vendor1)

	input_str2 := "playbooks/roles/create-venv/tasks/main.yaml"

	rawregex2, _ := regexp.MatchString(`(^|/)env/`, input_str2)
	fmt.Println("Raw regex:", rawregex2)

	vendor2 := enry.IsVendor(input_str2)
	fmt.Println("IsVendor:", vendor2)
}
```

When you run this the results are:

```
Raw regex: false
IsVendor: true
Raw regex: false
IsVendor: true
```

What this shows us is that the raw input regexes appear to behave as expected. Neither of our example input strings matches which is what we expect. But when we call `IsVendor()` the result becomes `true`. I suspect that the init function https://github.com/go-enry/go-enry/blob/7168084e5e5de38b915b1874528ff73f20a86b69/utils.go#L139-L246 is either adding rules that collide or introducing some bug to the expanded regex that causes this to happen.

**Comment by cboylan** [comment]
After downgrading enry to v2.6.1 my reproducer produces:

```
Raw regex: false
IsVendor: false
Raw regex: false
IsVendor: false
```

Every version release after v2.6.1 includes https://github.com/go-enry/go-enry/commit/20726a1de3cdff1d64bf0a6e5f6e2475a2c96913 which is what added the `init()` mangling of the regexes. I'm reasonably confident the issue is in the `init()` function now.

**Comment by cboylan** [comment]
The issue is that the generated regex looks a bit like this:

```
(?:^
    (?:[Dd]ependencies/)|
    (?:debian/)|
    (?:deps/)|
    (?:rebar$)
)|
(?:(?:^|/)
    (?:BuddyBuildSDK\\.framework/)|
    .
    .
    .
    (?:cache/)|
    .
    .
    .
```

The initial `^` and `^|/` only apply to the first regex in the OR'd listings. In this case `(?:[Dd]ependencies/)` and `(?:BuddyBuildSDK\\.framework/)`. They don't apply to the subsequently OR'd clauses which means they can match at any point in the string rather than with the `^` or `/` anchors.

**Comment by bzz** [comment]
Thank you for documenting detailed analysis and steps to reproduce!
