### ISSUE TITLE
Linguist release detection

### ISSUE THREAD

**Issue by DecimalTurn** [go-enry/go-enry#150]
The README states :

> There now is automation for detecting the changes in the upstream Linguist project: every day Github CI runs [a job](https://github.com/go-enry/go-enry/blob/master/.github/workflows/sync-linguist.yml) that will create a PR to this repo for each new Linguist release. It will include all the steps from the above.

However, I don't see any PRs for release [7.24.0](https://github.com/github/linguist/releases/tag/v7.24.0) or [7.24.1](https://github.com/github/linguist/releases/tag/v7.24.1). Was the automation turned off?

**Comment by bzz** [comment]
Thank you for your interest! It is actually working as expected - as soon as there is still an ongoing work on a release with 7.23 (#139  & co), it does not spam the developers with useless PRs (that will fail the CI anyway).

After that work will be merged - new PRs are going to show up 😉

**Comment by DecimalTurn** [comment]
> Thank you for your interest! It is actually working as expected - as soon as there is still an ongoing work on a release with 7.23 (https://github.com/go-enry/go-enry/pull/139 & co), it does not spam the developers with useless PRs (that will fail the CI anyway).

Oh, I see. This makes sense! Thank you for the clarification.

> After that work will be merged (soon™) - new PRs are going to show up 😉

Haha, yeah, I noticed that there was some work going on to make the tests pass, but it looks to me like you are on the right track.
Thanks again for your work! I'm closing this issue as my question was answered.
