### ISSUE TITLE
Separate detection of VBA (Visual Basic for Applications) and VB6 (Visual Basic 6.0)

### ISSUE THREAD

**Issue by King555a** [go-enry/go-enry#163]
While Linguist sees VBA (Visual Basic for Applications) and VB6 (Visual Basic 6.0) as two different languages (which they are), go-enry does not see that.

I have several repositories in Gitea, which uses go-enry, consisting of VB6 projects, but they are detected as VBA. I tried to use `linguist-language=vb6` to override it, which did not work. Then I saw that "vb6" is an alias for VBA in go-enry.

The name "VBA" for a VB6 project is just wrong. And, to be honest, it's a little bit derogatory.

I'm also wondering why VBA even exists in go-enry (and in Linguist), because VBA code is not in individual "VBA files", it's always in other documents like Word or Excel files.

**EDIT:** Now I read in the readme that overriding language detection is not possible currently. But it seems to be possible in Gitea. Nevertheless VBA and VB6 should be separated.

**EDIT 2:** I just checked and the files with the extensions frm, cls and bas, contrary to what I said, can be exported from Office (e.g. Excel), so they can exists "standalone" (which is usually not the case, I guess).

**EDIT 3:** These are the separated entries from linguist:

    VBA:
      type: programming
      color: "#867db1"
      extensions:
      - ".bas"
      - ".cls"
      - ".frm"
      - ".vba"
      tm_scope: source.vbnet
      aliases:
      - visual basic for applications
      ace_mode: text
      codemirror_mode: vb
      codemirror_mime_type: text/x-vb
      language_id: 399230729
    
    Visual Basic 6.0:
      type: programming
      color: "#2c6353"
      extensions:
      - ".cls"
      - ".ctl"
      - ".Dsr"
      - ".frm"
      tm_scope: source.vbnet
      aliases:
      - vb6
      - vb 6
      - visual basic 6
      - visual basic classic
      - classic visual basic
      ace_mode: text
      codemirror_mode: vb
      codemirror_mime_type: text/x-vb
      language_id: 679594952

**Comment by DecimalTurn** [comment]
The reason for this difference between Linguist and Enry is because Enry hasn't incorporated the changes from Linguist v7.24.1 yet.

**Comment by bzz** [comment]
Closing as https://github.com/go-enry/go-enry/releases/tag/v2.8.5 is out, with Linguist v7.26.0 support.
Please, feel free to re-open, if it is not working.
