### ISSUE TITLE
rust bindings not compiling

### ISSUE THREAD

**Issue by RoyalFoxy** [go-enry/go-enry#164]
I'm having trouble building my program which uses enrys rust bindings. I added following line into my cargo.toml `enry = { git = "https://github.com/go-enry/rs-enry", branch = "main" }` and tried `cargo build` which failed and outputed following error `could not find native static library "enry", perhaps an -L flag is missing?`. I have go installed and it is in my path. I even tried to clone go-enry myself and build it then putting the outputted file into `/usr/local/bin` which also didn't help. Also hadded the -L flag for cargos linker to look into `/usr/local/bin` which also didn't help. I tried to approximate the command in the [build.rs](https://github.com/go-enry/rs-enry/blob/main/build.rs) of the rust bindings repo which ended up being `go build -buildmode=c-archive -o ./libenry.a shared/enry.go` but that also errored out `go: no Go source files`. I'm not very familiar with go so I don't know where the entry point is and I think it doesn't properly compile because there hasn't been an update to the rust bindings in 2 years and enry itself is being updated frequently and maybe has changed the entry point or something along those lines...

**Comment by mkevre** [comment]
https://github.com/go-enry/go-enry/issues/164#issue-1632468953

**Comment by bzz** [comment]
> I tried to approximate the command in the [build.rs](https://github.com/go-enry/rs-enry/blob/main/build.rs) of the rust bindings

You are on the right track - enry library needs to be built from sources that are ventured as submodule, so you need to make sure those are checked out first, as described in https://github.com/go-enry/rs-enry#build 

Then `cargo build` should work. Let me know if that helps!
For the future, it might be better to keep track of any issues with the Rust bindings at the https://github.com/go-enry/rs-enry/issues

**Comment by bzz** [comment]
Please, feel free to re-open if the issue persists.

**Comment by RoyalFoxy** [comment]
I actually don't know if this persists. I kinda just stopped developing that project.
