### ISSUE TITLE
Alias names for languages not working(?)

### ISSUE THREAD

**Issue by King555a** [go-enry/go-enry#165]
I'm not sure whether this is a bug or I do not understand the method how go-enry works.

The problem is that the aliases for programming languages are not working, or at least it seems so to me.

I use "Gitea", which uses go-enry, and there I created a `.gitattributes` file with this content:

    *.bas linguist-language=vb6
    *.cls linguist-language=vb6
    *.frm linguist-language=vb6

According to https://github.com/go-gitea/gitea/issues/23417#issuecomment-1495189116 the color, for example, is retrieved by using `stats[i].Color = enry.GetColor(stats[i].Language)`. I guess `enry.GetColor` is part of go-enry (and not Gitea) and should get the color of the given string parameter. 

But `vb6` does not work (the correct color is not retrieved), although it's an alias name of `VBA` in go-enry. The two other aliases `visual basic 6` and `visual basic for applications` also do not work. The same goes when using `xhtml` instead of `HTML`.

**Comment by bzz** [comment]
Hi, I'm sorry, I have no idea about how Gitea works and weather it reads `.gitattributes`, may be @lafriks could help who also implemented `enry.GetColor` support in go-enry.

I do see that a [language "Visual Basic 6.0" has color assigned](https://github.com/go-enry/go-enry/blob/6d9d5e9184ca13d7ad34f77a6b4d5dd91d0f8b55/data/colors.go#L522), so probably `enry.GetColor("Visual Basic 6.0")` would return the `#2c6353`.

**Comment by lafriks** [comment]
Yes, this should be reported to Gitea as it is the one reading gitattributes file etc. Have to check how linguist/github is handling this but gitea should probably check language also aliases when parsing gitattributes to normalize language name
