### ISSUE TITLE
Detect autogenerated files

### ISSUE THREAD

**Issue by suhaibmujahid** [go-enry/go-enry#17]
Is there a plan to support auto-generated code files like in `github/linguist`
https://github.com/github/linguist/blob/master/lib/linguist/generated.rb

**Comment by lafriks** [comment]
I have a plan to work on this but most probably after a month or two if nobody have done it by then :)

**Comment by suhaibmujahid** [comment]
I never used Ruby, but I'm willing to help you when you work on it if you want.

**Comment by erizocosmico** [comment]
I'm currently working on this.
