### ISSUE TITLE
[Feature Request] Support Justfile

### ISSUE THREAD

**Issue by SteveLauC** [go-enry/go-enry#171]
It would be great if `go-enry` would support [justfile](https://github.com/casey/just) so that [Gitea could benefit from this](https://github.com/go-gitea/gitea/issues/27086):)

**Comment by bzz** [comment]
Go-enry is just a port to Go of the original [Linguist](https://github.com/github/linguist) Ruby library, so this request should be filed in there. As soon as it lands there, the next go-enry version will pull it automatically.

**Comment by SteveLauC** [comment]
>  As soon as it lands there, the next go-enry version will pull it automatically.

Seems that [the support for justfile has already been added to linguist](https://github.com/github-linguist/linguist/pull/6086) 

Should we bump the dependency in the `go-enry` side?

**Comment by bzz** [comment]
If you check which version of linguist was this change released at - you could check if the [latest go-enry release](https://github.com/go-enry/go-enry/releases) ships it.

**Comment by SteveLauC** [comment]
Linguist version [7.24.0](https://github.com/github-linguist/linguist/releases/tag/v7.24.0) contains that patch, and go-enry v.2.8.5 is the only version that ships it
