### ISSUE TITLE
[Feature] SQF code support

### ISSUE THREAD

**Issue by gru2007** [go-enry/go-enry#172]
# Feature Description

Please, add SQF code support 
go-gitea/gitea#27134

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/78332542/2633bb75-2f81-4ef3-85f7-c607acd73837)

**Comment by bzz** [comment]
go-enry is just a port to Go of the original [Linguist](https://github.com/github/linguist) Ruby library, so this request should be filed in there. As soon as it lands there, the next go-enry version will pull it automatically.

Closing it for now, but feel free to re-open in case something is not clear.
