### ISSUE TITLE
3dl files misclassified as Roff

### ISSUE THREAD

**Issue by tiltX** [go-enry/go-enry#175]
Files with the 3dl extension are 3D look-up tables used in image and video processing.

Enry classifies them as "Roff". I took a look at the code and it seems like the .3 extension is assigned to Roff because it's used by man pages. I can't figure out why .3dl falls into the same category since the lists in languageInfo.go and extension.go don't mention it. All I can see are .3in, .3m, .3p, .3pm, .3qt and .3x.

For me the issue would also be solved if I could make go-enry ignore .3dl files. They are neither code nor markup after all. I've found out about this because I'm using gitea, which uses go-enry. Should I raise the issue with them instead?

**Comment by bzz** [comment]
Thanks for the report. Gitea relies on Enry that follows the same rules as the https://github.com/github-linguist/linguist. 
So first thing is to check the version of enry you are using, then find appropriate version the linguist it is based upon (e.g. from enry GH release description) and see if it produces the same output over these files. If it does, this issue should be brought up & fixed upstream and the next enry release will include the fix automatically.

If the output is different - please feel free to re-open this issue we'll have to take a closer look.
