### ISSUE TITLE
Question. How do I perform analysis of a folder in another location.

### ISSUE THREAD

**Issue by wiliansilvazup** [go-enry/go-enry#25]
Ex .: using golang I would like to send the directory of a folder `/home/user/go/my-project` and go-enry returns all the languages used within this informed folder.

Using only golang is possible?

**Comment by bzz** [comment]
Hey @wiliansilvazup, sorry for delay, did you already had a chance to take a look at https://github.com/go-enry/enry/blob/master/main.go ? That is a Go program that traverses a given path and reports all the languages.

I hope that answers your question and so going to close the issue, but please, feel free to reopen it if that is not the case!
