### ISSUE TITLE
GetLanguagesByContent problem

### ISSUE THREAD

**Issue by ne1llee** [go-enry/go-enry#26]
![image](https://user-images.githubusercontent.com/12810839/84350002-1b2fc080-abeb-11ea-9fce-ba87d34b38eb.png)
Why does GetLanguagesByContent need a file extension?  
What do I do if I want to identify a file that has no extension?

**Comment by bzz** [comment]
Enry, [same as linguist](https://github.com/github/linguist#how-linguist-works), is designed around the sequence of strategies, each narrowing down the possible language options.

The API on the screenshot above (confusingly named) only runs the [regex heuristics](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml) over the file content to disambiguate between _languages sharing the same extension_ e.g. `.h` for [C++ and Objective-C](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml#L190).
