### ISSUE TITLE
Nim's language color

### ISSUE THREAD

**Issue by avahe-kellenberger** [go-enry/go-enry#32]
Nim's current language color it Gitea is green (#37775b), but Nim's official color is yellow (#ffe954).

Could we have it changed?

**Comment by smola** [comment]
@avahe-kellenberger go-enry imports most data, including colors, from [github/linguist](https://github.com/github/linguist/). If you want to change the color, you can open an issue at https://github.com/github/linguist/issues

The change will be eventually imported to go-enry.

**Comment by avahe-kellenberger** [comment]
Thanks!
