### ISSUE TITLE
There is a way to guess a language of files without without knowing the extension?

### ISSUE THREAD

**Issue by sbarex** [go-enry/go-enry#41]
Hi,
I would like to use this library to recognize the language starting from the content of the file only without knowing the extension.

The heuristic engine I have seen still requires the file extension to operate.

Why not have a Strategy that, in the absence of an extension, iterates through all those defined to see which ones satisfy the content of the file?

Something like this:

```go
func GetLanguagesByContent2(filename string, content []byte, _ []string) []string {
	if filename == "" {
		return nil
	}

	ext := strings.ToLower(filepath.Ext(filename))

	if ext != "" {
		return nil
	}
	result := []string {}
	for _, heuristic := range data.ContentHeuristics {
		r := heuristic.Match(content)
		if len(r) > 0 {
			result = append(result, r...)
		}
	}
	return result
}
```

**Comment by bzz** [comment]
Hi @sbarex - yes, that use-case is documented at https://github.com/go-enry/go-enry#by-text

Please, feel free to re-open if that does not answer your questions.
