### ISSUE TITLE
Automate Linguist updates with GitHub Actions

### ISSUE THREAD

**Issue by look** [go-enry/go-enry#51]
I spent a little time looking into automating Linguist updates with GitHub Actions.

I believe it could be implemented like this:

* Use a scheduled workflow run (once per day perhaps)
* In the workflow:
  * check out Linguist
  * find the most recent release tag
  * get its commit ID
  * put the commit ID in the generator_test.go file (could also put it in a `LINGUIST_REVISION` file and pull that into the test)
  * run `make code-generate`
  * Use an action to create a PR if there are any local diffs

[This Action](https://github.com/marketplace/actions/create-pull-request) seems to be the most popular one to create a Pull Request.

Getting this working will require a bit of trial and error but I think it would be worth it because Linguist updates will become very simple.

**Comment by bzz** [comment]
Indeed, that sounds feasible. The only thing is that the results of such update better to be "reviewable" manually somehow, as we have quite some https://github.com/go-enry/go-enry#divergences-from-linguist e.g. sometimes test have to be updated manually in order to pass (exclude some extensions), etc

**Comment by look** [comment]
Definitely, nothing would be merged automatically. I am happy to work on this, however it may require an access token in order to create PRs. At the very least, being able to create branches in this repository would make it easier to iterate on. I will see how far I can get in my fork and ping you with the results.
