### ISSUE TITLE
Support tm_scope and other fields from languages.yml

### ISSUE THREAD

**Issue by tclem** [go-enry/go-enry#54]
I'd like to know the `tm_scope` value for a given language. For example, if `Go` was detected as the programming language, the value would be [`source.go`](https://github.com/github/linguist/blob/19b3a9bd7d585be8d6459cfab0a51607b2aee68b/lib/linguist/languages.yml#L2015). Even better, it would be great for `GetLanguage` and friends (or some variant) to return a struct with all the information linguist stores with regard to a given language. It would also be fine to do this as secondary step:

```go
langName := enry.GetLanguage("foo.cpp", []byte("<cpp-code>"))
lang := enry.LookupLanguage(langName)
// where lang is a instance of struct like
type Language struct {
  Name string
  Type string
  Aliases []string
  Extensions []string
  TmScope string
  ... etc
}
```

**Comment by bzz** [comment]
In general, the plan with the secondary step sounds promising. 

ATM language information is only used at the generation phase, so the simplest way would be to add one more generator that produces a `language` -> `tm_scope` map stored in the `data/` + API call, similar to how `GetColor` was added in 25b29ebdc44f7640413095285099292bcd7ef754

**Comment by look** [comment]
@bzz how do you feel about a `Language` struct like @tclem proposes? I've considered this as well and I think it would be quite nice for many use cases.

**Comment by bzz** [comment]
> @bzz how do you feel about a `Language` struct like @tclem proposes? I've considered this as well and I think it would be quite nice for many use cases.

It seems reasonable, given that the implementation does not break existing API by forcing all the clients to migrate.
And the proposal with the second step looks as a nice way to do just that.

Also, may be, it would be worth having a separate issue for such a change then?
