### ISSUE TITLE
Would you take a Pull Request to expose C++ bindings?

### ISSUE THREAD

**Issue by EliSchleifer** [go-enry/go-enry#63]
Wondering if you would take a pull request to take C++ bindings?

**Comment by bzz** [comment]
Hey @EliSchleifer - after a discussion \w @mcuadros, we decided that best binding maintenance strategy going forward would be https://github.com/go-enry/go-enry/issues/31 - to host each of those in a separate git repository, like we did with https://github.com/go-enry/rs-enry

I have created https://github.com/go-enry/cpp-enry so if you feel like sharing your implementation and helping to maintain it as a part of the enry project - we'll be more than happy to have it there.

**Comment by EliSchleifer** [comment]
Great. Sounds like a plan
________________________________

**Comment by bzz** [comment]
https://github.com/go-enry/cpp-enry/pull/1 🚀
