### ISSUE TITLE
Linguist update automation opens multiple PRs

### ISSUE THREAD

**Issue by look** [go-enry/go-enry#69]
The Linguist update automation runs once a day, so if the generated PR isn't merged by then, it will open another one!

https://github.com/go-enry/go-enry/pull/68 #70

**Comment by look** [comment]
I think I can fix this by using a consistent branch name based on the linguist commit hash or tag name (commit hash would be more accurate if they happen to yank a release; tag name would be easier to read).

Instead of creating a new branch (which creates a new PR) every time the automation runs, it would check for the branch existing and exit if it already does.

Thoughts?

**Comment by lafriks** [comment]
Maybe we can use only tag name as branch and update existing branch if tag commit changes?

**Comment by bzz** [comment]
Checking for a branch name that is based on linguist's release tag sounds reasonable, even if does not handle the change of the tagged commits (as we do not check that for the old releases).

**Comment by look** [comment]
Sorry, this keeps happening and I haven't done anything about it. I'll work on a PR next week to fix it.
